            - name: Standard Ruby
  # You may pin to the exact commit or the version.
  # uses: packagespace/standard-ruby-action@a9050d2442db97288183940ce7e74e3b05f8e4ae
  uses: packagespace/standard-ruby-action@v1.0.3
  with:
    # The Ruby version specifier to pass to ruby/setup-ruby
    ruby-version: # optional, default is ruby
    # Whether autofixes should be committed back to the branch
    autofix: # optional, default is true
    # The working directory from which to run this action's commands. Default '.'
    workdir: # optional, default is .
          
